# -*- coding: utf-8 -*-
"""
ABINIT 引擎
=============
开源平面波DFT软件，擅长响应函数和声子计算
https://www.abinit.org/

输入文件: *.abi (Fortran namelist 风格)
输出文件: *.abo (标准输出)
"""

from extensions.engines.dft_engine import (
    DFTEngine, DFTTaskType, EngineCapability, InputFiles, ParsedResult
)
from typing import Dict, Any


class ABINITEngine(DFTEngine):
    """ABINIT 计算引擎"""

    def get_capability(self) -> EngineCapability:
        return EngineCapability(
            engine_name="abinit",
            display_name="ABINIT",
            version="9.x",
            description="开源DFT软件，支持平面波/PAW方法，"
                        "擅长声子、介电函数、光学性质等响应函数计算",
            supported_tasks=[
                DFTTaskType.SINGLE_POINT,
                DFTTaskType.OPTIMIZE,
                DFTTaskType.DOS,
                DFTTaskType.BAND,
                DFTTaskType.PHONON,
            ],
            executable="abinit",
            license_type="GPL-3.0",
            website="https://www.abinit.org/",
            file_format="Fortran namelist (.abi)",
        )

    def generate_input(self, task_type: DFTTaskType,
                       structure: Dict[str, Any],
                       params: Dict[str, Any]) -> InputFiles:
        """生成 ABINIT 输入文件"""
        elements = structure.get("elements", [])
        positions = structure.get("positions", [])
        cell = structure.get("cell", [[5, 0, 0], [0, 5, 0], [0, 0, 5]])
        unique_elems = list(dict.fromkeys(elements))

        # 元素 → znucl 映射 (常见元素)
        from core.constants import Constants
        znucl_list = []
        for elem in unique_elems:
            z = Constants.periodic_table.get(elem, 0)
            znucl_list.append(str(z))

        # typat: 每个原子的类型编号 (1-based)
        typat = [unique_elems.index(e) + 1 for e in elements]

        ecut_ha = params.get("ecut_ha",
                             params.get("encut", 400) / 27.2114)

        lines = [
            f"# ABINIT input generated by AlloyThermolCal Pro",
            f"# Task: {task_type.value}",
            "",
            f"ndtset 1",
            f"",
            f"# 基组",
            f"ecut {ecut_ha:.1f}",
            f"pawecutdg {ecut_ha * 2:.1f}",
            f"",
            f"# 体系",
            f"natom {len(elements)}",
            f"ntypat {len(unique_elems)}",
            f"znucl {' '.join(znucl_list)}",
            f"typat {' '.join(str(t) for t in typat)}",
            f"",
        ]

        # 晶胞
        lines.append("# 晶胞 (angstrom)")
        lines.append("acell 1.0 1.0 1.0 Angstr")
        lines.append("rprim")
        for vec in cell:
            lines.append(f"  {vec[0]:.10f}  {vec[1]:.10f}  {vec[2]:.10f}")
        lines.append("")

        # 原子位置
        lines.append("# 原子坐标 (Cartesian, angstrom)")
        lines.append("xangst")
        for pos in positions:
            lines.append(f"  {pos[0]:.10f}  {pos[1]:.10f}  {pos[2]:.10f}")
        lines.append("")

        # K点
        kpts = params.get("kpoints", "6 6 6")
        k_values = kpts.split()
        lines.append(f"ngkpt {kpts}")
        lines.append("shiftk 0.0 0.0 0.0")
        lines.append("")

        # 任务参数
        if task_type == DFTTaskType.OPTIMIZE:
            lines.append("ionmov 2")
            lines.append("optcell 2")
            lines.append(f"ntime {params.get('ntime', 50)}")
            lines.append(f"tolmxf {params.get('tolmxf', 5e-5)}")
        elif task_type == DFTTaskType.SINGLE_POINT:
            lines.append(f"toldfe {params.get('toldfe', 1e-10)}")
        elif task_type == DFTTaskType.DOS:
            lines.append(f"toldfe {params.get('toldfe', 1e-10)}")
            lines.append("prtdos 1")

        lines.append("")

        files = {"input.abi": "\n".join(lines) + "\n"}

        return InputFiles(
            files=files,
            work_dir_name=f"abinit_{task_type.value}",
            notes="PAW数据集需从 https://www.abinit.org/psp-tables 下载",
        )

    def parse_output(self, task_type: DFTTaskType,
                     output_files: Dict[str, str]) -> ParsedResult:
        """解析 ABINIT 输出"""
        result = ParsedResult()
        output = output_files.get("output.abo", "")
        if not output:
            return result

        ha_to_ev = 27.2114
        lines = output.strip().split("\n")

        for line in reversed(lines):
            if "etotal" in line.lower():
                try:
                    energy_ha = float(line.split()[-1])
                    result.total_energy_eV = energy_ha * ha_to_ev
                except (ValueError, IndexError):
                    pass
                break

        for line in reversed(lines):
            if "Calculation completed" in line:
                result.converged = True
                break
        else:
            result.converged = False

        return result

    def get_run_command(self, task_type: DFTTaskType,
                       n_cores: int = 1) -> str:
        if n_cores > 1:
            return f"mpirun -np {n_cores} abinit < input.abi > output.abo"
        return "abinit < input.abi > output.abo"
