# -*- coding: utf-8 -*-
"""
VASP 引擎
==========
Vienna Ab initio Simulation Package (商业软件)
https://www.vasp.at/

输入文件: POSCAR, INCAR, KPOINTS, POTCAR
输出文件: OUTCAR, vasprun.xml, CONTCAR, OSZICAR
"""

from extensions.engines.dft_engine import (
    DFTEngine, DFTTaskType, EngineCapability, InputFiles, ParsedResult
)
from typing import Dict, Any


class VASPEngine(DFTEngine):
    """VASP DFT 计算引擎"""

    def get_capability(self) -> EngineCapability:
        return EngineCapability(
            engine_name="vasp",
            display_name="VASP",
            version="6.x",
            description="Vienna Ab initio Simulation Package，"
                        "平面波赝势方法，广泛用于材料科学DFT计算",
            supported_tasks=[
                DFTTaskType.SINGLE_POINT,
                DFTTaskType.OPTIMIZE,
                DFTTaskType.DOS,
                DFTTaskType.BAND,
                DFTTaskType.MD,
                DFTTaskType.NEB,
            ],
            executable="vasp_std",
            license_type="commercial",
            website="https://www.vasp.at/",
            file_format="POSCAR/INCAR/KPOINTS/POTCAR",
        )

    def generate_input(self, task_type: DFTTaskType,
                       structure: Dict[str, Any],
                       params: Dict[str, Any]) -> InputFiles:
        """生成 VASP 输入文件"""
        files = {}
        elements = structure.get("elements", [])
        positions = structure.get("positions", [])
        cell = structure.get("cell", [[5, 0, 0], [0, 5, 0], [0, 0, 5]])

        # --- POSCAR ---
        unique_elems = list(dict.fromkeys(elements))
        counts = [elements.count(e) for e in unique_elems]
        poscar_lines = [
            "Generated by AlloyThermolCal Pro",
            "1.0",
        ]
        for vec in cell:
            poscar_lines.append(f"  {vec[0]:.10f}  {vec[1]:.10f}  {vec[2]:.10f}")
        poscar_lines.append("  ".join(unique_elems))
        poscar_lines.append("  ".join(str(c) for c in counts))
        poscar_lines.append("Cartesian")
        for pos in positions:
            poscar_lines.append(f"  {pos[0]:.10f}  {pos[1]:.10f}  {pos[2]:.10f}")
        files["POSCAR"] = "\n".join(poscar_lines) + "\n"

        # --- INCAR ---
        encut = params.get("encut", 400)
        incar_params = {
            "SYSTEM": "AlloyThermolCal",
            "ENCUT": encut,
            "EDIFF": params.get("ediff", 1e-6),
            "ISMEAR": params.get("ismear", 1),
            "SIGMA": params.get("sigma", 0.2),
            "PREC": params.get("prec", "Accurate"),
            "LREAL": params.get("lreal", "Auto"),
        }

        if task_type == DFTTaskType.SINGLE_POINT:
            incar_params["NSW"] = 0
            incar_params["IBRION"] = -1
        elif task_type == DFTTaskType.OPTIMIZE:
            incar_params["NSW"] = params.get("nsw", 100)
            incar_params["IBRION"] = params.get("ibrion", 2)
            incar_params["ISIF"] = params.get("isif", 3)
            incar_params["EDIFFG"] = params.get("ediffg", -0.01)
        elif task_type == DFTTaskType.DOS:
            incar_params["NSW"] = 0
            incar_params["IBRION"] = -1
            incar_params["LORBIT"] = 11
            incar_params["NEDOS"] = params.get("nedos", 3001)
        elif task_type == DFTTaskType.MD:
            incar_params["IBRION"] = 0
            incar_params["NSW"] = params.get("nsw", 1000)
            incar_params["POTIM"] = params.get("potim", 1.0)
            incar_params["SMASS"] = params.get("smass", 0)
            incar_params["TEBEG"] = params.get("temperature", 300)

        incar_content = ""
        for k, v in incar_params.items():
            incar_content += f"{k} = {v}\n"
        files["INCAR"] = incar_content

        # --- KPOINTS ---
        kpoints_str = params.get("kpoints", "6 6 6")
        files["KPOINTS"] = (
            "Automatic K-mesh\n"
            "0\n"
            "Gamma\n"
            f"  {kpoints_str}\n"
            "  0  0  0\n"
        )

        return InputFiles(
            files=files,
            work_dir_name=f"vasp_{task_type.value}",
            notes="POTCAR 需根据元素从赝势库中自行准备",
        )

    def parse_output(self, task_type: DFTTaskType,
                     output_files: Dict[str, str]) -> ParsedResult:
        """解析 VASP OUTCAR"""
        result = ParsedResult()
        outcar = output_files.get("OUTCAR", "")

        if not outcar:
            return result

        lines = outcar.strip().split("\n")
        for line in reversed(lines):
            if "free  energy   TOTEN" in line:
                try:
                    result.total_energy_eV = float(line.split()[-2])
                except (ValueError, IndexError):
                    pass
                break

        for line in lines:
            if "number of ions" in line:
                try:
                    n_ions = int(line.split()[-1])
                    if result.total_energy_eV is not None:
                        result.energy_per_atom_eV = result.total_energy_eV / n_ions
                except (ValueError, IndexError):
                    pass
                break

        for line in reversed(lines):
            if "reached required accuracy" in line:
                result.converged = True
                break
        else:
            result.converged = False

        return result

    def get_run_command(self, task_type: DFTTaskType,
                       n_cores: int = 1) -> str:
        if n_cores > 1:
            return f"mpirun -np {n_cores} vasp_std"
        return "vasp_std"

    def estimate_time(self, task_type: DFTTaskType,
                      n_atoms: int,
                      params: Dict[str, Any]) -> Dict[str, Any]:
        """VASP 计算时间粗略估算"""
        base = {
            DFTTaskType.SINGLE_POINT: 300,
            DFTTaskType.OPTIMIZE: 1800,
            DFTTaskType.DOS: 600,
            DFTTaskType.BAND: 900,
            DFTTaskType.MD: 7200,
            DFTTaskType.NEB: 14400,
        }.get(task_type, 3600)
        scale = max(1, n_atoms / 4)
        return {"estimated_seconds": int(base * scale), "confidence": "low"}
